name: Build App
on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        description: OS to build on. Ubuntu is faster, MacOS supports iOS builds, Windows is unsupported
        options:
          - macos-latest
          - ubuntu-latest
      platform:
        type: choice
        description: Platform to build for
        options:
          - android
          - ios
      profile:
        type: choice
        description: Build profile to use
        options:
          - preview:device
          - preview:simulator
          - dev:device
          - dev:simulator
jobs:
  build:
    runs-on: ${{ github.event.inputs.os }}
    strategy:
      matrix:
        node: [18.x]
    steps:
    - name: 🏗 Setup repo
      uses: actions/checkout@v3

    - name: 🏗 Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: yarn

    - name: 🏗 Setup Expo and EAS
      uses: expo/expo-github-action@v8
      with:
        token: ${{ secrets.EXPO_TOKEN }}
        expo-version: latest
        eas-version: latest

    - name: 🏗 Setup EAS local builds
      run: yarn global add eas-cli-local-build-plugin

    - name: 📦 Install dependencies
      run: yarn

    - name: 👷 Build app
      run: |
        cd packages/app && eas build --local \
          --non-interactive \
          --output=./app-build \
          --platform=${{ github.event.inputs.platform }} \
          --profile=${{ github.event.inputs.profile }}

    - name: 📱 Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: app-${{ github.event.inputs.platform }}
        path: ./packages/app/app-build
